#version: '3.8'

services:
  metalreleasetracker.backgroundservices:
    image: metalreleasetrackerbackgroundservices
    build:
      context: .
      dockerfile: MetalReleaseTracker.BackgroundServices/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - postgres-main
      - postgres-background
      - seq-background  
    entrypoint: /bin/bash -c "dotnet ef database update --project /src/MetalReleaseTracker.Infrastructure/MetalReleaseTracker.Infrastructure.csproj --startup-project /src/MetalReleaseTracker.API/MetalReleaseTracker.API.csproj && dotnet MetalReleaseTracker.BackgroundServices.dll"
    
  metalreleasetracker.api:
    image: metalreleasetrackerapi 
    build:
      context: .
      dockerfile: MetalReleaseTracker.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    restart: unless-stopped
    ports:
     - "8080:8080"
     - "8081:8081"
    networks:
      - app-network
    depends_on:
      - postgres-main
      - seq-main
    entrypoint: /bin/bash -c "dotnet ef database update --project /src/MetalReleaseTracker.Infrastructure/MetalReleaseTracker.Infrastructure.csproj --startup-project /src/MetalReleaseTracker.API/MetalReleaseTracker.API.csproj && dotnet MetalReleaseTracker.API.dll"

  postgres-main:
    image: postgres:16
    environment:
      POSTGRES_DB: MetalReleaseTrackerDb
      POSTGRES_USER: metal
      POSTGRES_PASSWORD: Mtl_pswrdSl
    ports:
      - "5433:5432"
    volumes:
      - postgres-main-data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres-background:
    image: postgres:16
    environment:
      POSTGRES_DB: BackgroundServicesDb
      POSTGRES_USER: metalUser
      POSTGRES_PASSWORD: Mtl_EApswrd
    ports:
      - "5434:5432"
    volumes:
      - postgres-background-data:/var/lib/postgresql/data 
    networks:
      - app-network

  seq-main:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    networks:
      - app-network
    restart: unless-stopped

  seq-background:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5342:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-main-data:
  postgres-background-data:
